### ISSUE TITLE
Some problem about GLP420 challenge

### ISSUE THREAD

**Issue by y011d4** [cryptohack/ctf_archive#17]
Thanks for merging https://github.com/cryptohack/ctf_archive/pull/15
But one of the challenges, GLP420, doesn't show anything by `nc archive.cryptohack.org 26931`.
In my environment, I can connect by `nc localhost 1337` after `docker build -t tmp` and `docker run -d -p 1337:1337 --name tmp tmp`. So I don't know why it doesn't work in cryptohack env.

Would you please check what's going on in the server?

**Comment by y011d4** [comment]
2mins after connection, it shows "Killed"

**Comment by hyperreality** [comment]
It must be something related to Sage, unexpectedly this is actually the first server challenge we have that is running on Sage so we don't really have anything to compare it to.

But, most likely this is caused by the pretty aggressive CPU and memory limits we set on the containers:
```
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 50M 
```

Sage normally requires far more memory than this. And actually, the server we use is not really powerful enough to run more than one or two Sage instances so I'm not really sure about tweaking this now.

Is it okay if we remove this challenge?

**Comment by y011d4** [comment]
I see. thank you for explanation!
So I'll make a PR to remove this challenge.
